Import OpenWrt tree from RUT2XX_R_GPL_00.01.10

diff --git a/package/network/services/openvpn/files/openvpn.init b/package/network/services/openvpn/files/openvpn.init
--- a/package/network/services/openvpn/files/openvpn.init
+++ b/package/network/services/openvpn/files/openvpn.init
@@ -10,11 +10,80 @@ STOP=10
 USE_PROCD=1
 PROG=/usr/sbin/openvpn
 
+CCD_ARGS=""
 LIST_SEP="
 "
+ENABLED=0
+OPENVPN_CONFIG=""
 
-UCI_STARTED=
-UCI_DISABLED=
+# generates selective config file for specific
+# client and integrates client parameters into
+# global OpenVPN server logic (routes, pushs etc.)
+config_client() {
+	local section_id="$1"
+	local snip="$2"
+	local snm="$3"
+	local cn
+	local lip
+	local rip
+	local pip
+	local pnm
+	local sname
+
+	# get client params from /etc/config/openvpn
+	config_get cn "$section_id" cn
+	config_get lip "$section_id" lip
+	config_get rip "$section_id" rip
+	config_get pip "$section_id" pip
+	config_get pnm "$section_id" pnm
+	config_get sname "$section_id" sname
+
+	# generate selective config in /etc/openvpn/ccd
+	printf "--ifconfig-push %s %s\n" "$lip" "$rip" > /etc/openvpn/ccd/$cn
+	printf "--iroute %s %s\n" "$pip" "$pnm" >> /etc/openvpn/ccd/$cn
+	printf "--push route %s %s\n" "$snip" "$snm" >> /etc/openvpn/ccd/$cn
+
+	# store temporary data
+	printf "--push route %s %s\n" "$pip" "$pnm" >> /etc/openvpn/ccd/plist.tmp
+	printf "--route %s %s " "$pip" "$pnm" >> /etc/openvpn/ccd/rlist.tmp
+}
+
+prepare_clients() {
+	local sip=`uci get network.lan.ipaddr`
+	local snm=`uci get network.lan.netmask`
+	local snip=`ipcalc.sh "$sip" "$snm" | grep NETWORK | cut -d= -f2`
+
+	init_ccd
+	config_foreach config_client 'client' "$snip" "$snm"
+	add_server_routes
+	add_interclient_routes
+}
+
+init_ccd() {
+	if [ ! -d /var/etc/openvpn-ccd ]; then
+		mkdir -p /var/etc/openvpn-ccd
+	fi
+
+	if [ -h /etc/openvpn/ccd ]; then
+		rm /etc/openvpn/ccd/* 2>/dev/null
+	else
+		ln -s /var/etc/openvpn-ccd /etc/openvpn/ccd
+	fi
+}
+
+add_server_routes() {
+	CCD_ARGS=`cat /etc/openvpn/ccd/rlist.tmp 2>/dev/null`
+	rm /etc/openvpn/ccd/rlist.tmp 2>/dev/null
+}
+
+add_interclient_routes() {
+	for f in `ls /etc/openvpn/ccd/`; do
+		if [ "$f" != /etc/openvpn/ccd/plist.tmp ]; then
+			cat /etc/openvpn/ccd/plist.tmp 2>/dev/null >> "$f"
+		fi
+	done
+	rm /etc/openvpn/ccd/plist.tmp 2>/dev/null
+}
 
 append_param() {
 	local s="$1"
@@ -24,15 +93,20 @@ append_param() {
 		*_*_*)   v=${v%%_*}-${v#*_}; v=${v%%_*}-${v#*_} ;;
 		*_*)     v=${v%%_*}-${v#*_} ;;
 	esac
-	echo -n "$v" >> "/var/etc/openvpn-$s.conf"
+	echo -n "$v" >> "$OPENVPN_CONFIG"
 	return 0
+}
+
+append_extended_params() {
+	local arg="$1"
+	[ -n "$arg" ] && echo "$arg" | sed -e 's/^[ \t]*//' >> "$OPENVPN_CONFIG"
 }
 
 append_bools() {
 	local p; local v; local s="$1"; shift
 	for p in $*; do
 		config_get_bool v "$s" "$p"
-		[ "$v" = 1 ] && append_param "$s" "$p" && echo >> "/var/etc/openvpn-$s.conf"
+		[ "$v" = 1 ] && append_param "$s" "$p" && echo >> "$OPENVPN_CONFIG"
 	done
 }
 
@@ -42,7 +116,12 @@ append_params() {
 		config_get v "$s" "$p"
 		IFS="$LIST_SEP"
 		for v in $v; do
-			[ -n "$v" ] && append_param "$s" "$p" && echo " $v" >> "/var/etc/openvpn-$s.conf"
+			#if for quatation marks for push options, openvpn 2.4 fails without it
+			if [ "$p" = "push" ];then
+				[ -n "$v" ] && append_param "$s" "$p" && echo " \"$v\"" >> "$OPENVPN_CONFIG"
+			else
+				[ -n "$v" ] && append_param "$s" "$p" && echo " $v" >> "$OPENVPN_CONFIG"
+			fi
 		done
 		unset IFS
 	done
@@ -58,43 +137,54 @@ openvpn_add_instance() {
 	local name="$1"
 	local dir="$2"
 	local conf="$3"
+	local stat="$4"
+	local CCD=""
 
-	procd_open_instance
+	[ "$name" != "teltonika_auth_service" ] && CCD=$CCD_ARGS
+
+	if [ "$name" == "teltonika_auth_service" ]; then
+		procd_open_instance rms
+	else
+		procd_open_instance $name
+	fi
 	procd_set_param command "$PROG"	\
 		--syslog "openvpn($name)" \
-		--status "/var/run/openvpn.$name.status" \
 		--cd "$dir" \
-		--config "$conf"
+		--config "$conf" \
+		--status "$stat" \
+		$CCD
 	procd_set_param file "$dir/$conf"
-	procd_set_param respawn
+	if [ "$1" == "teltonika_auth_service" ]; then
+
+		procd_set_param respawn ${respawn_threshold:-0} ${respawn_timeout:-120} ${respawn_retry:-0}
+	else
+		procd_set_param respawn
+	fi
 	procd_close_instance
 }
 
 start_instance() {
 	local s="$1"
 
-	config_get config "$s" config
-	config="${config:+$(readlink -f "$config")}"
+	OPENVPN_CONFIG="/var/etc/openvpn-$s.conf"
 
-	section_enabled "$s" || {
-		append UCI_DISABLED "$config" "$LIST_SEP"
-		return 1
-	}
+	section_enabled "$s" || return 0
+
+	config_get config "$s" config
 
 	[ ! -d "/var/run" ] && mkdir -p "/var/run"
 
 	if [ ! -z "$config" ]; then
-		append UCI_STARTED "$config" "$LIST_SEP"
-		openvpn_add_instance "$s" "${config%/*}" "$config"
+		openvpn_add_instance "$s" "$(dirname "$config")" "$(basename "$config")" "/tmp/openvpn-$s.status"
 		return
 	fi
 
 	[ ! -d "/var/etc" ] && mkdir -p "/var/etc"
-	[ -f "/var/etc/openvpn-$s.conf" ] && rm "/var/etc/openvpn-$s.conf"
+	[ -f "$OPENVPN_CONFIG" ] && rm "$OPENVPN_CONFIG"
 
 	# append flags
 	append_bools "$s" \
-		auth_nocache auth_user_pass_optional bind ccd_exclusive client client_cert_not_required \
+		auth_nocache auth_retry auth_user_pass_optional bind ccd_exclusive client client_cert_not_required \
 		client_to_client comp_noadapt disable \
 		disable_occ down_pre duplicate_cn fast_io float http_proxy_retry \
 		ifconfig_noexec ifconfig_nowarn ifconfig_pool_linear management_forget_disconnect management_hold \
@@ -107,7 +197,7 @@ start_instance() {
 
 	# append params
 	append_params "$s" \
-		cd askpass auth auth_retry auth_user_pass auth_user_pass_verify bcast_buffers ca cert \
+		cd askpass auth auth_user_pass auth_user_pass_verify bcast_buffers ca cert \
 		chroot cipher client_config_dir client_connect client_disconnect comp_lzo connect_freq \
 		connect_retry connect_timeout connect_retry_max crl_verify dev dev_node dev_type dh \
 		echo engine explicit_exit_notify fragment group hand_window hash_size \
@@ -115,7 +205,7 @@ start_instance() {
 		ifconfig_pool_persist ifconfig_push inactive ipchange iroute keepalive \
 		key key_method keysize learn_address link_mtu lladdr local log log_append \
 		lport management management_log_cache max_clients \
-		max_routes_per_client mode mssfix mtu_disc mute nice ns_cert_type ping \
+		max_routes_per_client max_routes mode mssfix mtu_disc mute nice ns_cert_type ping \
 		ping_exit ping_restart pkcs12 plugin port port_share prng proto rcvbuf \
 		redirect_gateway remap_usr1 remote remote_cert_eku remote_cert_ku remote_cert_tls \
 		reneg_bytes reneg_pkts reneg_sec \
@@ -126,29 +216,37 @@ start_instance() {
 		tun_mtu tun_mtu_extra txqueuelen user verb down push up \
 		ifconfig_ipv6 route_ipv6 server_ipv6 ifconfig_ipv6_pool ifconfig_ipv6_push iroute_ipv6
 
-	openvpn_add_instance "$s" "/var/etc" "openvpn-$s.conf"
+	config_list_foreach "$s" "_extra" append_extended_params
+
+	openvpn_add_instance "$s" "/var/etc" "openvpn-$s.conf" "/tmp/openvpn-$s.status"
+}
+
+delete_status() {
+	rm -rf /tmp/openvpn-$1.status
+}
+
+checkifenabled() {
+	section_enabled $1
+	if [ $? -eq 0 ]; then
+		ENABLED=1
+	fi
+}
+
+service_triggers()
+{
+	procd_add_reload_trigger "openvpn"
 }
 
 start_service() {
 	config_load 'openvpn'
+	config_foreach checkifenabled 'openvpn'
+	[ $ENABLED -eq 0 ] && return 1
+
+	prepare_clients
 	config_foreach start_instance 'openvpn'
+}
 
-	local path name
-	for path in /etc/openvpn/*.conf; do
-		if [ -f "$path" ]; then
-			name="${path##*/}"; name="${name%.conf}"
-
-			# don't start configs again that are already started by uci
-			if echo "$UCI_STARTED" | grep -qxF "$path"; then
-				continue
-
-			# don't start configs which are set to disabled in uci
-			elif echo "$UCI_DISABLED" | grep -qxF "$path"; then
-				logger -t openvpn "$name.conf is disabled in /etc/config/openvpn"
-				continue
-			fi
-
-			openvpn_add_instance "$name" "${path%/*}" "$path"
-		fi
-	done
+stop_service() {
+	config_load 'openvpn'
+	config_foreach delete_status 'openvpn'
 }
